### ISSUE TITLE
Feature: User can search for holidays

### ISSUE THREAD

**Issue by derrenpamintuan** [derrenpamintuan/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Apply CSS to the header for the web page.
- [x] Add a `div[data-view="search-form"]` to the HTML.
- [x] Create a form that:
- [x] has search bar that only takes in 2 letters.
- [x] Create a table to the HTML.
- [x] Add an eventListener on submit for the search bar that fetches data from the API.
- [x] Create new elements from the eventListener on submit to the table by using DOM creation.
- [x] Apply CSS to ensure that the display looks nice on both mobile and desktop screen.
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
