### ISSUE TITLE
Feature: User can save holidays

### ISSUE THREAD

**Issue by derrenpamintuan** [derrenpamintuan/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add icons next to the holidays that change colors when a user click on it.
- [x] Within the addEventListener for the html table, create an object that stores the values from the api and store it into an array.
- [x] Add an eventListener on the window that has a beforeunload event that saves the data to the users local storage.
- [x] Add a function in renderRow that saves the icon a user has already clicked so they cannot click it again.
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
