### ISSUE TITLE
Feature: User can view a list of their favorite holidays

### ISSUE THREAD

**Issue by derrenpamintuan** [derrenpamintuan/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create a unordered list in HTML that has a view property of saved favorites.
- [x] Add some dummy journal entries and style them according to the Figma design. Each content should be in a single li element within the ul.
- [x] Create a function named renderSaved with a single parameter 'saved'. This parameter represents a single object for a single holiday from the data.holidays array. This function should generate and return a DOM tree for a single holiday that matches the holidays you created in the unordered list.
- [x] Add a function called view-swap with a single parameter representing the name of the view to show (the value will either be "search-view" or "saved-view". This function should show the view whose name was provided as an argument, as well as assign the string argument to the data.view property so that the currently shown view is tracked in the data model for the application.
- [x] Add an icon to the header of the page that switches views to the users favorites list.
- [x] Add an icon to the header of the page that switches views to the search view.
- [x] Create a viewSwap function that swaps views of what is being displayed.
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
